# Generated by Django 5.1 on 2024-09-02 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('banco', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('conta', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('bancoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minha_app.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, default='/images/placehold.png', null=True, upload_to='images/')),
                ('bi_frente', models.ImageField(blank=True, default='/images/placehold1.png', null=True, upload_to='images/')),
                ('bi_verso', models.ImageField(blank=True, default='/images/placehold2.png', null=True, upload_to='images/')),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minha_app.banco')),
                ('conta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minha_app.conta')),
            ],
        ),
    ]
